<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kinko</string>
	</array>
	<key>name</key>
	<string>Kinko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(def|if-some|if|each|let)\b</string>
			<key>name</key>
			<string>keyword.control.kinko</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:\w+</string>
			<key>name</key>
			<string>keyword.other.keyword.kinko</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[\w\.]+</string>
			<key>name</key>
			<string>keyword.other.placeholder.kinko</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kinko</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kinko</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kinko</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.kinko</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_kinko</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.kinko</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.kinko</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.kinko</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolated_kinko</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.kinko</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.kinko</string>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.kinko</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.kinko</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.kinko</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.kinko</string>
	<key>uuid</key>
	<string>F98B477B-8475-4764-BB24-3562511066F6</string>
</dict>
</plist>
